In [4]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [5]:
import numpy as np

In [6]:
np.__version__

'2.2.3'

In [14]:
#NUMPY ARRAYS:It is a collection of data type or elements
#Numpy arrays are the foundation of most numerical computing in python
#Because they offer efficient ways to store and manipulate large datasets.
#There are several ways to create different types of array
my_list=[1,2,3,4,5]
Data = np.array(my_list)
print(Data)


[1 2 3 4 5]


In [ ]:
type(Data)
Data.dtype #dtype is used to show the data types of elements in an array.
#dtype can be used to specify which kind of data one wants.
list=[1.5,2.3,3.7]
data1= np.array(list,dtype=int)
data1#As shown i i nputed a list of float data type but later it gave me a full number interger.

array([1, 2, 3])

In [ ]:
data1.size#the size function is used to show the number of elements in an array.

3

In [24]:
#MULTI_DIMENSIONAL ARRAYS
#1D array-A single row item
#2D array-A table like data with rows and columns 
#3D array_It is a series of multiple tables(2d arrays)stack togeother
#2d array
list1= [1,2,3,4]
list2=[5,6,7,8]
array2d = np.array([list1,list2])
print(array2d)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
Data.ndim#You can check the arrays if it is either 1,2 or 3

1

In [31]:
array3d= np.array([
    [[1,2,3],[4,5,6]],[[7,8,9],[1,2,3]]
                                     ])
array3d
#array3d.ndim

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [1, 2, 3]]])

In [32]:
#Zeros function;zeros function is used to create an array filled with zero elements
#It is usedful if one wants to create a placeholder arrays with specific dimensions such as initializing weights for machine learning models,preparing matrices for computations
#How to create zero array
zero_array = np.zeros(5)
print(zero_array)

[0. 0. 0. 0. 0.]


In [33]:
zero_2darray = np.zeros((3,5))#3 rep rows & 5 reps column
print(zero_2darray)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
zero_2darray.shape#Used to check,the number of rows and column

(3, 5)

In [ ]:
zero_3darray =np.zeros((2,3,4),dtype=int)#One can specify data type of elements.
print(zero_3darray)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [36]:
zero_3darray.ndim

3

In [38]:
#np ones creates elements filled with ones,simolar to np.zeros

In [40]:
arrayones1=np.ones(4)
print(arrayones1)

[1. 1. 1. 1.]


In [42]:
arrayones2 =np.ones((2,4))
print(arrayones2)
arrayones2.ndim

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


2

In [45]:
arrayones3 = np.ones((3,2,3))
print(arrayones3)
arrayones3.size

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


18

In [ ]:
#np.eye() this function creates a 2d array(matrix) with ones on the main diagonal  and zeros everywhere else
#This matrix is called identity matrix.Identity matrix are wdely  used in linear algebra.because it is used widely used in linear algebra as the multiplicative identity
identy_matrix= np.eye(4,4)#(n,m)
print(identy_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [52]:
#One can move the m values above or below using the m values
indentity_matrix=np.eye (4,4, k=-2)
print(indentity_matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]


In [57]:
#np.full:This function creates an array filled with specified value which can be any number you choose.Simillar to np.ones() and np.zeros()
twosarray = np.full(5,6)#colums,#Element
print(twosarray)

#2d array
arrayfull2d =np.full((3,2,3),3)
print(arrayfull2d)


[6 6 6 6 6]
[[[3 3 3]
  [3 3 3]]

 [[3 3 3]
  [3 3 3]]

 [[3 3 3]
  [3 3 3]]]


In [59]:
#np.arange():This function is used to create an array with evely spaced values within a given interval.
#It is similar to the built-in python range function,but it returns a list instead.It allows floating points as well as full intergers.
#np.arange(start,stop,step,dtype)==>it is not inclusive of the stop number.
arr =np.arange(1,10,3, dtype=float)
print(arr)

[1. 4. 7.]
