In [ ]:
#There are several numpy functions useful in my data science journey.
#np.reshape()==>It allows one to change the shape/dimensions of any array without altering it's data.
#Rule:The total number of elements in the old array must match the new shape.Used to change 1D array to 2D array.
import numpy as np

In [5]:
array1 = np.array([1,2,3,4,5,6,7,8])
print(array1)#2D arrays have a row and column information.
array_reshape = np.reshape(array1,(2,4))
print(array_reshape)#The elements of the first array should be equal to the second
array_3d = np.reshape(array1,(2,2,2))
print(array_3d)

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [9]:
#np.max:It return the maximum number in the array.Either the array is 2d,3d or d.
array_random =np.random.randint(10,30,15)
print(array_random)
np.max(array_random)

[17 25 18 15 21 10 14 10 14 24 18 28 20 29 21]


np.int32(29)

In [15]:
arrayrandom2 =np.random.randint(5,20, (5,4))
print(arrayrandom2)
maximumval =np.max(arrayrandom2)
print(maximumval)

[[ 7 17 13 12]
 [15 12 16 18]
 [ 9  8 13 18]
 [16 13  8 16]
 [10  5  5  9]]
18


In [ ]:
#How to find maximum values as per row/column
maximum_col = np.max(arrayrandom2, axis=0)#0 stands for column direction
print(maximum_col)
maximum_row = np.max(arrayrandom2, axis=1)#Where axis = 1 stands row direction.
print(maximum_row)

[16 17 16 18]
[17 18 18 16 10]
